/** Reusable CHIEF agent templates (sandbox-safe). */

export type AgentTemplateDef = {
  slug: string;
  name: string;
  description: string;
  category: string;
  architecture: Record<string, unknown>;
  defaultTools: { toolId: string; scope: string }[];
  evalHarness: { name: string; assert: string }[];
  starterCode: string;
};

export const BUILTIN_TEMPLATES: AgentTemplateDef[] = [
  {
    slug: "internal-ops-status",
    name: "Internal Ops Status Reporter",
    description:
      "Sandboxed internal agent that reads platform/org health metrics and emits a structured status brief. No external side effects.",
    category: "INTERNAL",
    architecture: {
      runtime: "json-runner",
      isolation: "sandbox",
      sideEffects: "none",
      inputs: ["organizationId?"],
      outputs: ["statusBrief"],
    },
    defaultTools: [
      { toolId: "org.metrics.read", scope: "READ" },
      { toolId: "platform.health.read", scope: "READ" },
      { toolId: "agent.report.write", scope: "WRITE" },
    ],
    evalHarness: [
      { name: "returns_status_shape", assert: "output.hasStatus" },
      { name: "no_unrestricted_tools", assert: "tools.sanitized" },
      { name: "deterministic_brief", assert: "output.hasBrief" },
    ],
    starterCode: `/**
 * Internal Ops Status Reporter — generated by CHIEF Foundry.
 * Runtime: sandboxed JSON+function runner (no network, no credential access).
 */
export const meta = {
  slug: "internal-ops-status",
  version: 1,
  sideEffects: "none",
};

export function run(input, ctx) {
  const metrics = ctx.tools["org.metrics.read"](input) || {};
  const health = ctx.tools["platform.health.read"](input) || {};
  const brief = {
    generatedAt: new Date().toISOString(),
    status: health.ok === false ? "DEGRADED" : "OK",
    orgOpportunityCount: metrics.opportunityCount ?? null,
    orgInefficiencyCount: metrics.inefficiencyCount ?? null,
    pendingApprovals: metrics.pendingApprovals ?? null,
    healthNote: health.note || "Platform health probe",
    integrationGaps: health.missingIntegrations || [],
  };
  ctx.tools["agent.report.write"]({ brief });
  return { ok: true, brief, hasStatus: true, hasBrief: true };
}
`,
  },
  {
    slug: "security-intake-recorder",
    name: "Security Spec Intake Recorder",
    description:
      "Records CSEO security-agent specifications into structured intake records. Does not deploy or grant tools.",
    category: "SECURITY_INTAKE",
    architecture: {
      runtime: "json-runner",
      isolation: "sandbox",
      sideEffects: "db-write-intake-only",
    },
    defaultTools: [{ toolId: "audit.append", scope: "WRITE" }],
    evalHarness: [
      { name: "rejects_empty_spec", assert: "output.rejectsEmpty" },
      { name: "no_self_privilege", assert: "tools.sanitized" },
    ],
    starterCode: `export const meta = { slug: "security-intake-recorder", sideEffects: "db-write-intake-only" };
export function run(input, ctx) {
  if (!input || !input.title) return { ok: false, rejectsEmpty: true };
  ctx.tools["audit.append"]({ action: "security_spec.recorded", title: input.title });
  return { ok: true, rejectsEmpty: false, recorded: true };
}
`,
  },
];

export function matchTemplate(instruction: string): AgentTemplateDef {
  const lower = instruction.toLowerCase();
  if (lower.includes("security") || lower.includes("cseo") || lower.includes("intake")) {
    return BUILTIN_TEMPLATES.find((t) => t.slug === "security-intake-recorder")!;
  }
  return BUILTIN_TEMPLATES.find((t) => t.slug === "internal-ops-status")!;
}
