/** Reusable CHIEF agent templates — sandbox runners + live website/app packages. */

import { generateWebBundle, webAgentRunnerSource, type WebRuntime } from "./webgen";

export type AgentTemplateDef = {
  slug: string;
  name: string;
  description: string;
  category: string;
  architecture: Record<string, unknown>;
  defaultTools: { toolId: string; scope: string }[];
  evalHarness: { name: string; assert: string }[];
  starterCode: string;
  /** When set, Foundry generates a real HTML package for same-domain live deploy. */
  webRuntime?: WebRuntime;
};

export const BUILTIN_TEMPLATES: AgentTemplateDef[] = [
  {
    slug: "internal-ops-status",
    name: "Internal Ops Status Reporter",
    description:
      "Sandboxed internal agent that reads platform/org health metrics and emits a structured status brief. No external side effects.",
    category: "INTERNAL",
    architecture: {
      runtime: "json-runner",
      isolation: "sandbox",
      sideEffects: "none",
      inputs: ["organizationId?"],
      outputs: ["statusBrief"],
    },
    defaultTools: [
      { toolId: "org.metrics.read", scope: "READ" },
      { toolId: "platform.health.read", scope: "READ" },
      { toolId: "agent.report.write", scope: "WRITE" },
    ],
    evalHarness: [
      { name: "returns_status_shape", assert: "output.hasStatus" },
      { name: "no_unrestricted_tools", assert: "tools.sanitized" },
      { name: "deterministic_brief", assert: "output.hasBrief" },
    ],
    starterCode: `/**
 * Internal Ops Status Reporter — generated by CHIEF Foundry.
 * Runtime: sandboxed JSON+function runner (no network, no credential access).
 */
export const meta = {
  slug: "internal-ops-status",
  version: 1,
  sideEffects: "none",
};

export function run(input, ctx) {
  const metrics = ctx.tools["org.metrics.read"](input) || {};
  const health = ctx.tools["platform.health.read"](input) || {};
  const brief = {
    generatedAt: new Date().toISOString(),
    status: health.ok === false ? "DEGRADED" : "OK",
    orgOpportunityCount: metrics.opportunityCount ?? null,
    orgInefficiencyCount: metrics.inefficiencyCount ?? null,
    pendingApprovals: metrics.pendingApprovals ?? null,
    healthNote: health.note || "Platform health probe",
    integrationGaps: health.missingIntegrations || [],
  };
  ctx.tools["agent.report.write"]({ brief });
  return { ok: true, brief, hasStatus: true, hasBrief: true };
}
`,
  },
  {
    slug: "security-intake-recorder",
    name: "Security Spec Intake Recorder",
    description:
      "Records CSEO security-agent specifications into structured intake records. Does not deploy or grant tools.",
    category: "SECURITY_INTAKE",
    architecture: {
      runtime: "json-runner",
      isolation: "sandbox",
      sideEffects: "db-write-intake-only",
    },
    defaultTools: [{ toolId: "audit.append", scope: "WRITE" }],
    evalHarness: [
      { name: "rejects_empty_spec", assert: "output.rejectsEmpty" },
      { name: "no_self_privilege", assert: "tools.sanitized" },
    ],
    starterCode: `export const meta = { slug: "security-intake-recorder", sideEffects: "db-write-intake-only" };
export function run(input, ctx) {
  if (!input || !input.title) return { ok: false, rejectsEmpty: true };
  ctx.tools["audit.append"]({ action: "security_spec.recorded", title: input.title });
  return { ok: true, rejectsEmpty: false, recorded: true };
}
`,
  },
  {
    slug: "static-site",
    name: "Static Site / Status Page",
    description:
      "Generates a real static HTML/CSS/JS microsite (e.g. internal status page) and deploys it live at /a/<slug> after human approval.",
    category: "STATIC_SITE",
    webRuntime: "static-site",
    architecture: {
      runtime: "static-site",
      isolation: "same-domain-public",
      sideEffects: "none",
      deployAdapter: "same-domain",
      livePath: "/a/<slug>",
      outputs: ["index.html", "styles.css", "app.js", "health.json"],
    },
    defaultTools: [
      { toolId: "platform.health.read", scope: "READ" },
      { toolId: "agent.report.write", scope: "WRITE" },
    ],
    evalHarness: [
      { name: "has_html", assert: "output.hasHtml" },
      { name: "has_title", assert: "output.hasTitle" },
      { name: "no_unrestricted_tools", assert: "tools.sanitized" },
      { name: "returns_status_shape", assert: "output.hasStatus" },
    ],
    starterCode: webAgentRunnerSource("static-site", "Internal Status Page"),
  },
  {
    slug: "web-app",
    name: "Mini Web App",
    description:
      "Generates a small interactive web app (client-side) and deploys it live at /a/<slug> after human approval.",
    category: "WEB_APP",
    webRuntime: "web-app",
    architecture: {
      runtime: "web-app",
      isolation: "same-domain-public",
      sideEffects: "browser-local-only",
      deployAdapter: "same-domain",
      livePath: "/a/<slug>",
    },
    defaultTools: [{ toolId: "agent.report.write", scope: "WRITE" }],
    evalHarness: [
      { name: "has_html", assert: "output.hasHtml" },
      { name: "has_title", assert: "output.hasTitle" },
      { name: "no_unrestricted_tools", assert: "tools.sanitized" },
    ],
    starterCode: webAgentRunnerSource("web-app", "Mini App"),
  },
  {
    slug: "next-microsite",
    name: "Next Microsite (static emit)",
    description:
      "Landing / marketing microsite packaged as static HTML and served under Kaivaryn /a/<slug> (no separate Render billing).",
    category: "WEB_APP",
    webRuntime: "next-microsite",
    architecture: {
      runtime: "next-microsite",
      isolation: "same-domain-public",
      sideEffects: "none",
      deployAdapter: "same-domain",
      livePath: "/a/<slug>",
      note: "Emitted as static HTML compatible with Next hosting; not a separate Next process.",
    },
    defaultTools: [{ toolId: "agent.report.write", scope: "WRITE" }],
    evalHarness: [
      { name: "has_html", assert: "output.hasHtml" },
      { name: "has_title", assert: "output.hasTitle" },
      { name: "no_unrestricted_tools", assert: "tools.sanitized" },
    ],
    starterCode: webAgentRunnerSource("next-microsite", "Public Microsite"),
  },
];

export function matchTemplate(instruction: string): AgentTemplateDef {
  const lower = instruction.toLowerCase();

  // Security intake first (keep existing behavior)
  if (
    (lower.includes("security") || lower.includes("cseo") || lower.includes("intake")) &&
    !lower.includes("landing") &&
    !lower.includes("website") &&
    !lower.includes("microsite") &&
    !lower.includes("web app") &&
    !lower.includes("status page")
  ) {
    return BUILTIN_TEMPLATES.find((t) => t.slug === "security-intake-recorder")!;
  }

  // Live website / app agents
  if (
    lower.includes("web app") ||
    lower.includes("mini app") ||
    lower.includes("mini-app") ||
    (lower.includes("app that") && (lower.includes("build") || lower.includes("manufacture")))
  ) {
    return BUILTIN_TEMPLATES.find((t) => t.slug === "web-app")!;
  }
  if (
    lower.includes("landing") ||
    lower.includes("marketing site") ||
    lower.includes("microsite") ||
    lower.includes("next-microsite")
  ) {
    return BUILTIN_TEMPLATES.find((t) => t.slug === "next-microsite")!;
  }
  if (
    lower.includes("status page") ||
    lower.includes("static site") ||
    lower.includes("static-site") ||
    lower.includes("website") ||
    lower.includes("web page") ||
    lower.includes("live page") ||
    (lower.includes("build") && lower.includes("page"))
  ) {
    return BUILTIN_TEMPLATES.find((t) => t.slug === "static-site")!;
  }

  return BUILTIN_TEMPLATES.find((t) => t.slug === "internal-ops-status")!;
}

/** Build web bundle for a template+instruction+slug (used by Foundry generate). */
export function buildTemplateWebBundle(template: AgentTemplateDef, instruction: string, slug: string) {
  if (!template.webRuntime) return null;
  return generateWebBundle({ runtime: template.webRuntime, instruction, slug });
}
