import type { VendorGuide } from "./types";
import { CONFIRM } from "./shared";
import { g } from "./make";

const COLLAB_SHARE = ["Named channels / sites / drives in scope", "Shared calendars or documents only if you choose to share them"];
const HR_SHARE = ["Headcount by department / location", "Hire and termination dates (no SSN / bank details)", "Job titles and managers", "Payroll cost summaries if you choose to share them"];
const FLEX_SHARE = ["The files or endpoints you and your Kaivaryn lead agree on"];

export const COLLAB_GUIDES: VendorGuide[] = [
  g("slack", "oauth", "collab", "Slack apps are installed by a workspace admin (or a member, if your workspace allows) on Slack's own authorization screen.",
    ["A Slack workspace admin (or a member allowed to install apps)."],
    ["On the setup call, open the Slack install link your Kaivaryn lead sends.", "Approve only the read scopes needed for the channels you named.", "Add those channel names to the intake below."],
    COLLAB_SHARE, ["If you prefer not to connect Slack, share specific channel export files with your Kaivaryn lead during setup."],
    "https://api.slack.com/authentication/oauth-v2"),
  g("teams", "oauth", "collab", "Microsoft Teams access uses Microsoft Entra app consent by a tenant admin (or users, depending on your tenant policy).",
    ["A Microsoft 365 / Entra admin, or a user allowed to consent to apps."],
    ["On the setup call, approve Kaivaryn's Microsoft consent screen for the Teams / Graph scopes agreed.", "Limit access to the teams / channels named in the intake.", "Add those teams / channels to the intake below."],
    COLLAB_SHARE, ["Export chat / channel history only if your compliance policy allows, and upload agreed files in Kaivaryn → Imports."],
    "https://learn.microsoft.com/en-us/graph/auth-v2-user"),
  g("google_workspace", "oauth", "collab", "Google Workspace access uses a Google Cloud OAuth consent (or a domain-wide delegated service account for admin-managed setups).",
    ["A Google Workspace admin for domain-wide setups, or a user who can approve the app.", `Domain-wide delegation vs. user OAuth — ${CONFIRM}.`],
    ["On the setup call, approve Kaivaryn's Google consent screen for the Drive / Sheets / Calendar scopes agreed — or have your admin configure domain-wide delegation.", "Limit access to the shared drives / folders named in the intake.", "Add those drives / folders and your company domain to the intake below."],
    COLLAB_SHARE, ["Share specific Sheets / Drive folders with your Kaivaryn lead's Google account, or export CSVs and upload them in Kaivaryn → Imports."],
    "https://developers.google.com/identity/protocols/oauth2"),
  g("microsoft365", "oauth", "collab", "Microsoft 365 access uses Microsoft Entra app consent for Graph (SharePoint, Excel, Outlook, Calendar).",
    ["A Microsoft 365 / Entra admin, or a user allowed to consent to apps."],
    ["On the setup call, approve Kaivaryn's Microsoft consent screen for the Graph scopes agreed.", "Limit access to the SharePoint sites / mailboxes named in the intake.", "Add those sites / mailboxes and your tenant domain to the intake below."],
    COLLAB_SHARE, ["Export Excel / SharePoint lists as CSV and upload them in Kaivaryn → Imports."],
    "https://learn.microsoft.com/en-us/graph/auth-v2-user"),
  g("notion", "oauth", "collab", "Notion integrations are authorized by a workspace owner / admin; pages are shared with the integration explicitly.",
    ["A Notion workspace owner or admin."],
    ["On the setup call, install Kaivaryn's Notion integration (or create an internal integration) and share only the pages / databases in scope.", "Add those page / database names to the intake below."],
    COLLAB_SHARE, ["Export Notion databases as CSV / Markdown and upload them in Kaivaryn → Imports."],
    "https://developers.notion.com/docs/authorization"),
];

export const HR_GUIDES: VendorGuide[] = [
  g("workday", "partner_request", "hr", "Workday integrations typically go through Workday's ISU (integration system user) and reports-as-a-service, set up by your Workday admin / partner.",
    ["A Workday administrator or your Workday implementation partner."],
    ["Tell your Kaivaryn lead which Workday modules you use (HCM, Payroll, Time).", "Your Workday admin creates an Integration System User with least-privilege domains for the reports agreed.", "Hand access over live with your Kaivaryn lead.", "Add departments, headcount, and pay period to the intake below."],
    HR_SHARE, ["Export the agreed Workday reports as CSV / Excel and upload them in Kaivaryn → Imports."],
    "https://doc.workday.com/"),
  g("bamboohr", "api_credentials", "hr", "BambooHR API keys are created by an account admin under Settings → Apps → API Keys.",
    ["A BambooHR account admin."],
    ["In BambooHR, open Settings → Apps (or Account) → API Keys and create a key.", "Hand the key to your Kaivaryn lead live on the call — never by email or in this form.", "Add departments and headcount to the intake below."],
    HR_SHARE, ["Export employee directory / reports as CSV and upload them in Kaivaryn → Imports."],
    "https://documentation.bamboohr.com/docs/getting-started"),
  g("adp", "partner_request", "payroll", "ADP Workforce Now and RUN integrations go through ADP's partner / marketplace programs; Kaivaryn does not claim an ADP partnership.",
    ["Your ADP administrator and ADP account rep."],
    ["Tell your Kaivaryn lead which ADP product you use (Workforce Now, RUN, etc.).", "Ask your ADP rep about the approved data-share path for Kaivaryn; meanwhile use payroll / labor exports.", "Export payroll summaries (no bank / SSN) and upload them in Kaivaryn → Imports.", "Add pay groups and pay period to the intake below."],
    HR_SHARE, ["Export payroll / labor reports weekly or each pay period and upload them."],
    "https://developers.adp.com/"),
  g("ukg", "partner_request", "payroll", "UKG (Dimensions / Pro) integrations are typically arranged through UKG and your implementation partner.",
    ["Your UKG administrator and UKG / partner contact."],
    ["Tell your Kaivaryn lead which UKG product you use.", `Ask UKG about the approved data-share path — ${CONFIRM}.`, "Meanwhile, export schedule and labor reports and upload them in Kaivaryn → Imports.", "Add pay groups, overtime rule, and locations to the intake below."],
    HR_SHARE, ["Export labor / timesheet reports each pay period and upload them."],
    "https://developer.ukg.com/"),
  g("gusto", "oauth", "payroll", "Gusto apps are authorized by a company admin on Gusto's own consent screen (or via Gusto's partner programs).",
    ["A Gusto company admin / payroll admin."],
    ["On the setup call, open the Gusto authorization link your Kaivaryn lead sends (or confirm the partner path).", "Approve read-only access to company, employees, and payrolls.", "Add pay groups and pay period to the intake below."],
    HR_SHARE, ["Export payroll reports from Gusto as CSV and upload them in Kaivaryn → Imports."],
    "https://docs.gusto.com/embedded-payroll/docs/authentication"),
];

export const FLEX_GUIDES: VendorGuide[] = [
  g("csv", "file", "flexible", "A controlled file import — the fastest way to start while a direct connection is planned.",
    ["Someone who can export the source system as CSV / Excel."],
    ["Pick the reports / tables you and your Kaivaryn lead agree on.", "Export them as CSV (UTF-8) with a header row.", "Upload them in Kaivaryn → Imports and map the columns together.", "Agree a cadence (weekly is common) and stick to the same column layout."],
    FLEX_SHARE, ["Repeat the same export on the agreed cadence and upload it."],
    "https://kaivaryn.onrender.com/app/imports"),
  g("sftp", "file", "flexible", "A scheduled secure file drop from your systems or a partner.",
    ["An IT contact who can write to an SFTP location.", `Kaivaryn-hosted vs. customer-hosted SFTP — ${CONFIRM}.`],
    ["Agree the folder layout and file naming with your Kaivaryn lead.", "Your IT team writes the agreed CSVs on the agreed cadence.", "Kaivaryn picks them up and maps columns the same way as a File import.", "Add the source system and cadence to the intake below."],
    FLEX_SHARE, ["Place a weekly CSV in the agreed folder using the agreed name pattern."],
    "https://kaivaryn.onrender.com/app/imports"),
  g("rest_api", "partner_request", "flexible", "A custom REST API or internal service your team exposes for Kaivaryn to read.",
    ["An engineering / IT contact who owns the API.", "A staging environment preferred for first testing."],
    ["Share the OpenAPI / endpoint list (read-only) with your Kaivaryn lead.", "Agree authentication (OAuth client credentials or a signed key) and hand credentials over live.", "Agree the objects and refresh cadence.", "Add the source system and cadence to the intake below."],
    FLEX_SHARE, ["Until the API is live, export the same objects as CSV and upload them in Kaivaryn → Imports."],
    "https://kaivaryn.onrender.com/app/integrations"),
  g("webhooks", "partner_request", "flexible", "Near-real-time events pushed from a source system to Kaivaryn.",
    ["An engineering contact who can emit webhooks.", "Agreement on the event types and payload shape."],
    ["Agree the event list (for example order.created, ticket.updated) with your Kaivaryn lead.", "Kaivaryn provides a signed inbound URL for your tenant.", "Your system posts events; Kaivaryn verifies the signature and records them.", "Add the source system to the intake below."],
    FLEX_SHARE, ["A daily digest CSV of the same events works as a fallback."],
    "https://kaivaryn.onrender.com/app/integrations"),
  g("manual", "file", "flexible", "Start with operator-entered evidence before connecting systems.",
    ["An operator who will enter the first cases."],
    ["Agree the first operating question with your Kaivaryn lead.", "Enter evidence in Kaivaryn (findings / action center) without a system connection.", "Graduate to a File import or direct connection when you're ready."],
    ["The cases and evidence you enter by hand"], ["No recurring export — you enter what matters."],
    "https://kaivaryn.onrender.com/app"),
];

/** Honest generic template for "Other …" long-tail options. */
export const OTHER_GUIDES: VendorGuide[] = [
  g("other_crm", "export", "crm", "For a CRM that isn't listed, we start with a CSV export and confirm any direct path with you and the vendor during setup.",
    ["An admin for that CRM."],
    ["Tell us the product name and edition in the intake notes.", "Export deals / opportunities and accounts as CSV.", "Upload them in Kaivaryn → Imports.", `Any direct connection path is ${CONFIRM}.`],
    ["Opportunities / deals", "Accounts / contacts", "Owners"], [`Export weekly from your CRM — menu ${CONFIRM}.`],
    "https://kaivaryn.onrender.com/app/integrations"),
  g("other_erp", "export", "erp", "For an ERP / finance system that isn't listed, we start with controlled exports.",
    ["A finance / IT admin for that system."],
    ["Tell us the product name and edition.", "Export AR, AP, and the chart of accounts.", "Upload them in Kaivaryn → Imports.", `Any direct connection path is ${CONFIRM}.`],
    ["AR / AP", "Chart of accounts", "Entities"], [`Export weekly — menu ${CONFIRM}.`],
    "https://kaivaryn.onrender.com/app/integrations"),
  g("other_support", "export", "support", "For a help desk that isn't listed, we start with ticket CSV exports.",
    ["An admin for that help desk."],
    ["Tell us the product name.", "Export tickets with status, priority, assignee, and timestamps.", "Upload them in Kaivaryn → Imports."],
    ["Tickets", "Queues", "Agents"], [`Export weekly — menu ${CONFIRM}.`],
    "https://kaivaryn.onrender.com/app/integrations"),
  g("other_commerce", "export", "commerce", "For a store / marketplace that isn't listed, we start with order CSV exports.",
    ["An admin for that commerce platform."],
    ["Tell us the product name.", "Export orders, refunds, and products.", "Upload them in Kaivaryn → Imports."],
    ["Orders", "Refunds", "Products"], [`Export weekly — menu ${CONFIRM}.`],
    "https://kaivaryn.onrender.com/app/integrations"),
  g("other_ops", "export", "work", "For an operations / work system that isn't listed, we start with project / work-order CSV exports.",
    ["An admin for that system."],
    ["Tell us the product name.", "Export work items with status, owner, and dates.", "Upload them in Kaivaryn → Imports."],
    ["Work items", "Statuses", "Owners"], [`Export weekly — menu ${CONFIRM}.`],
    "https://kaivaryn.onrender.com/app/integrations"),
  g("other_warehouse", "database", "data", "For a warehouse / database that isn't listed, your IT team creates a least-privilege read-only user, or we start with exports.",
    ["A DBA / data engineer for that store."],
    ["Tell us the product name and version.", "Create a read-only user on the agreed schemas / views, or export them as CSV.", "Hand access over live with your Kaivaryn lead, or upload the CSVs in Kaivaryn → Imports."],
    DATA_SHARE_PLACEHOLDER(), [`Export the agreed views weekly — ${CONFIRM}.`],
    "https://kaivaryn.onrender.com/app/integrations"),
  g("other_hr", "export", "hr", "For an HR / payroll system that isn't listed, we start with headcount and payroll-summary exports (no SSN / bank details).",
    ["An HR / payroll admin."],
    ["Tell us the product name.", "Export headcount and payroll summaries (no sensitive IDs).", "Upload them in Kaivaryn → Imports."],
    ["Headcount", "Payroll summaries", "Departments"], [`Export each pay period — ${CONFIRM}.`],
    "https://kaivaryn.onrender.com/app/integrations"),
  g("pos_other", "export", "pos", "For a POS that isn't listed, we map what it can export during setup and start with back-office CSVs.",
    ["A POS admin who can run reports."],
    ["Tell us the POS name and version in the “Other POS” field.", "Export sales, comps / voids / discounts, refunds, menu mix, payments, and labor for the last full week.", "Upload them in Kaivaryn → Imports.", `Any direct connection path is ${CONFIRM}.`],
    ["Sales & checks", "Comps / voids / discounts", "Refunds", "Labor", "Payments"], [`Export weekly from your POS back office — menu ${CONFIRM}.`],
    "https://kaivaryn.onrender.com/app/integrations"),
];

function DATA_SHARE_PLACEHOLDER() { return ["The specific tables / views agreed in the intake", "A sample of recent rows for verification"]; }
