/**
 * The full business-system catalog shown in onboarding (all industries). Pure data.
 * Restaurant add-on systems live in @/lib/industry/restaurant and are merged in ALL_SYSTEMS.
 */
import { RESTAURANT_GROUPS } from "@/lib/industry/restaurant";

export type CatalogOption = readonly [key: string, name: string, description: string];

export const GENERAL_GROUPS = [
  { title: "CRM & customer systems", description: "Pipeline, accounts, customer history, and relationship signals.", options: [["salesforce", "Salesforce", "CRM, pipeline, opportunity, and account data."], ["hubspot", "HubSpot", "CRM, marketing, sales, and service activity."], ["dynamics365", "Microsoft Dynamics 365", "Customer, sales, finance, and operations records."], ["zoho", "Zoho CRM", "Accounts, deals, activities, and customer lifecycle."], ["pipedrive", "Pipedrive", "Sales pipeline and deal movement."], ["other_crm", "Other CRM", "A different customer system or custom CRM."]] },
  { title: "Finance, billing & ERP", description: "Invoices, payments, contracts, margin, purchasing, and financial controls.", options: [["stripe", "Stripe", "Payments, invoices, subscriptions, and failed payments."], ["quickbooks", "QuickBooks", "Accounting, invoices, payments, and receivables."], ["xero", "Xero", "Accounting, billing, reconciliation, and cash signals."], ["netsuite", "Oracle NetSuite", "ERP, finance, orders, purchasing, and inventory."], ["sap", "SAP", "Enterprise finance, procurement, order, and operations data."], ["sage", "Sage", "Accounting, payroll, finance, and business operations."], ["other_erp", "Other ERP / finance system", "A different ERP, accounting, or billing platform."]] },
  { title: "Support & service", description: "Tickets, conversations, response times, escalations, and service delivery.", options: [["zendesk", "Zendesk", "Support tickets, SLA performance, and customer issues."], ["intercom", "Intercom", "Customer conversations, support, and engagement."], ["servicenow", "ServiceNow", "Enterprise incidents, requests, and workflow queues."], ["jira_service", "Jira Service Management", "Service requests, incidents, and engineering handoffs."], ["other_support", "Other support desk", "A different help desk or service platform."]] },
  { title: "Commerce & subscriptions", description: "Orders, carts, subscriptions, product revenue, and customer conversion.", options: [["shopify", "Shopify", "Orders, customers, products, carts, and payments."], ["woocommerce", "WooCommerce", "Store orders, products, customers, and checkout activity."], ["magento", "Adobe Commerce / Magento", "Enterprise commerce, orders, and catalog signals."], ["chargebee", "Chargebee", "Subscriptions, churn, billing, and renewals."], ["other_commerce", "Other commerce platform", "A different store, marketplace, or subscription system."]] },
  { title: "Work management & operations", description: "Projects, work orders, queues, process steps, and operational throughput.", options: [["jira", "Jira", "Engineering work, cycle time, blockers, and delivery."], ["asana", "Asana", "Projects, tasks, owners, deadlines, and workload."], ["monday", "Monday.com", "Work boards, workflows, owners, and status."], ["servicenow_ops", "ServiceNow Operations", "Operational workflows, incidents, and queues."], ["smartsheet", "Smartsheet", "Structured work plans, projects, and approvals."], ["other_ops", "Other operations system", "A different work-order, project, or process platform."]] },
  { title: "Data warehouse & databases", description: "A governed source for analytics, historical records, and cross-system signals.", options: [["snowflake", "Snowflake", "Cloud warehouse and governed analytical data."], ["bigquery", "Google BigQuery", "Warehouse and event data at scale."], ["redshift", "Amazon Redshift", "AWS analytical warehouse data."], ["postgres", "PostgreSQL", "Operational or analytical relational data."], ["sql_server", "Microsoft SQL Server", "Enterprise relational and reporting data."], ["databricks", "Databricks", "Lakehouse, analytics, and machine learning data."], ["other_warehouse", "Other warehouse / database", "A different governed data store."]] },
  { title: "Collaboration & productivity", description: "The communication and document context around decisions and work.", options: [["slack", "Slack", "Team conversations, alerts, and operating handoffs."], ["teams", "Microsoft Teams", "Collaboration, messages, and team coordination."], ["google_workspace", "Google Workspace", "Drive, Sheets, Docs, and organizational context."], ["microsoft365", "Microsoft 365", "SharePoint, Excel, Outlook, and organizational context."], ["notion", "Notion", "Knowledge base, project notes, and operating documentation."]] },
  { title: "People & workforce", description: "Capacity, staffing, role, payroll, and workforce context for efficiency analysis.", options: [["workday", "Workday", "People, organization, workforce, and capacity data."], ["bamboohr", "BambooHR", "People records and workforce context."], ["adp", "ADP", "Payroll, workforce, and labor cost signals."], ["ukg", "UKG", "Workforce management, scheduling, and labor data."], ["gusto", "Gusto", "Payroll, benefits, and hours for small and mid-size teams."], ["other_hr", "Other HR / workforce system", "A different people, payroll, or workforce platform."]] },
  { title: "Flexible data exchange", description: "Use these when a named connector is not the right first path.", options: [["csv", "CSV / spreadsheet upload", "Start with a controlled file import and mapping review."], ["sftp", "SFTP / secure file drop", "Scheduled secure files from internal or partner systems."], ["rest_api", "REST API", "A custom API or internal service connection."], ["webhooks", "Webhooks / event stream", "Near-real-time events from a source system."], ["manual", "Manual review only", "Begin with operator-entered evidence before connecting systems."]] },
] as const;

export type CatalogSystem = { key: string; name: string; description: string; group: string; restaurant: boolean };

export const ALL_SYSTEMS: CatalogSystem[] = [
  ...RESTAURANT_GROUPS.flatMap((g) => g.options.map((o) => ({ key: o.key, name: o.name, description: o.description, group: g.title, restaurant: true }))),
  ...GENERAL_GROUPS.flatMap((g) => g.options.map(([key, name, description]) => ({ key, name, description, group: g.title, restaurant: false }))),
];

const BY_KEY = new Map(ALL_SYSTEMS.map((s) => [s.key, s]));
export const catalogSystem = (key: string) => BY_KEY.get(key) ?? null;
export const isCatalogKey = (key: string) => BY_KEY.has(key);
export const systemName = (key: string) => BY_KEY.get(key)?.name ?? key;
